<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="2" failed="0" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-09-17T20:31:24 IST" name="Default suite" finished-at="2025-09-17T20:31:24 IST" duration-ms="93">
    <groups>
    </groups>
    <test started-at="2025-09-17T20:31:24 IST" name="Default test" finished-at="2025-09-17T20:31:24 IST" duration-ms="93">
      <class name="com.company.attendance.service.LeaveServiceTest">
        <test-method is-config="true" signature="setUp()[pri:0, instance:com.company.attendance.service.LeaveServiceTest@4b8ee4de]" started-at="2025-09-17T20:31:24 IST" name="setUp" finished-at="2025-09-17T20:31:24 IST" duration-ms="13" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="testApplyAndApproveLeave()[pri:0, instance:com.company.attendance.service.LeaveServiceTest@4b8ee4de]" started-at="2025-09-17T20:31:24 IST" name="testApplyAndApproveLeave" finished-at="2025-09-17T20:31:24 IST" duration-ms="11" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testApplyAndApproveLeave -->
        <test-method signature="testInvalidDateRangeThrowsException()[pri:0, instance:com.company.attendance.service.LeaveServiceTest@4b8ee4de]" started-at="2025-09-17T20:31:24 IST" name="testInvalidDateRangeThrowsException" finished-at="2025-09-17T20:31:24 IST" duration-ms="2" status="PASS">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[End date cannot be before start date.]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: End date cannot be before start date.
at com.company.attendance.service.LeaveService.applyForLeave(LeaveService.java:16)
at com.company.attendance.service.LeaveServiceTest.testInvalidDateRangeThrowsException(LeaveServiceTest.java:40)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testInvalidDateRangeThrowsException -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:com.company.attendance.service.LeaveServiceTest@4b8ee4de]" started-at="2025-09-17T20:31:24 IST" name="setUp" finished-at="2025-09-17T20:31:24 IST" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
      </class> <!-- com.company.attendance.service.LeaveServiceTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
